### ISSUE TITLE
Could you rename variables like this to something more clear?

### ISSUE THREAD

**Issue by dpriskorn** [csisc/OpenCitations-Bot#1]
https://github.com/csisc/OpenCitations-Bot/blob/cbdead75068eb99238b33d1873a091dd3d6c62b3/OCtoWikidata.py#L11

The code gets hard to read when variables have short names. I use PyCharm to refactor variable names to something meaningful when needed. It automatically updates all occurrences. :)

**Comment by csisc** [comment]
Added comments to explain the algorithm.
