### ISSUE TITLE
Add "reference URL" and "retrieved" statements in reference field

### ISSUE THREAD

**Issue by diegodlh** [csisc/OpenCitations-Bot#12]
The OpenCitations bot now adds a "stated in: CITO" statement in the reference field of the statements it creates. I think it may be useful to also add "reference URL" and "retrieved" statements.

See for example what another bot ([LargeDatasetBot](https://www.wikidata.org/wiki/User:LargeDatasetBot)) did in [Q93088591](https://www.wikidata.org/wiki/Q93088591).

So, for example, item [Q107998450](https://www.wikidata.org/wiki/Q107998450) created by the OpenCitations bot could have had "https://opencitations.net/index/api/v1/metadata/10.1017/s0031182098003400" as "reference URL".

"cites work" statements, on the other hand, could have "reference URL" starting with "https://opencitations.net/index/api/v1/references/", I guess.

**Comment by csisc** [comment]
Of course, this can be done. I will work on this now.

**Comment by csisc** [comment]
Done. Solved. I added "https://opencitations.net/index/coci/api/v1/" as a reference URL as generating a new reference URL for every new statement is time-consuming. I also added the current date to all the references.
