### ISSUE TITLE
check missing? 

### ISSUE THREAD

**Issue by dpriskorn** [csisc/OpenCitations-Bot#19]
https://github.com/csisc/OpenCitations-Bot/blob/74d5983423ec8a0414f3289c97743e205bd685d8/OCtoWikidata.py#L50
Are you checking if the item already cites this work before appending?
It seems like this could cause a lot of duplications in cited work

**Comment by csisc** [comment]
No, we are not using fast run. When I did the tests on the statements, I found that the WikibaseIntegrator library verifies the existence of the Wikidata Statement before adding it.
