### ISSUE TITLE
Will this append cause duplicates on existing items?

### ISSUE THREAD

**Issue by dpriskorn** [csisc/OpenCitations-Bot#28]
https://github.com/csisc/OpenCitations-Bot/blob/91f3a7d47bc6896bfc6d7bb8392b7a197aef9b41/OCtoWikidata.py#L54

**Comment by csisc** [comment]
No, when we do not use fast run, it does not cause duplicates. I have tested this. However, it can add a new reference to the Wikidata statement every time.
