### ISSUE TITLE
move config in separate file

### ISSUE THREAD

**Issue by dpriskorn** [csisc/OpenCitations-Bot#3]
https://github.com/csisc/OpenCitations-Bot/blob/1c1410ec1770f7b5e122acb5841b62233f2abfcf/OCtoWikidata.py#L6
it is risky to have the config in the same file as the rest of the code. someone might accidentally share their credentials

**Comment by csisc** [comment]
This is absolutely true. I can add a few lines where the user is asked to create a file where he puts his credentials. However, I think that this will only add to the complexity of the Python code without any added value.

**Comment by dpriskorn** [comment]
I agree that it adds complexity. Alternatively you could warn users in the Readme perhaps?

**Comment by csisc** [comment]
Done. Thank you for sharing this.
