### ISSUE TITLE
No Wikidata ID exists

### ISSUE THREAD

**Issue by dpriskorn** [csisc/OpenCitations-Bot#4]
I recommend you to be more specific. In this case QID. Also consider renaming the variable and check the qid for validity using my class in LexODS
https://github.com/csisc/OpenCitations-Bot/blob/1c1410ec1770f7b5e122acb5841b62233f2abfcf/OCtoWikidata.py#L23

**Comment by csisc** [comment]
I am actually extracting this information from the list of James Hare. There is consequently no need to verify it. I expanded the comment to explain this.
